### ISSUE TITLE
feature: 5.45的义军武器可以自己分配副属性

### ISSUE THREAD

**Issue by trim21** [Asvel/ffxiv-gearing#11]

**Comment by Asvel** [comment]
这个我过段时间做吧，离义军武器进 BiS 还有些时间（躺平。

**Comment by trim21** [comment]
已经是5.45绝亚的bis了（小声）

**Comment by Asvel** [comment]
对哦，甚至可以直接按475武器的上限分配属性。

**Comment by trim21** [comment]
有义军武器的页面也没法导入了（

**Comment by Asvel** [comment]
哪个配装工具的，来个链接？

**Comment by trim21** [comment]
https://etro.gg/gearset/80f6a905-2677-49f6-8044-574352ebab39

（（

**Comment by Asvel** [comment]
简单修复了一下，虽然仍然导入不了自定义属性，但不会卡住了。

**Comment by Asvel** [comment]
做好了做好了_(┐「ε:)_。

**Comment by trim21** [comment]
爱您
