### ISSUE TITLE
store导出了装备id变成了负值

### ISSUE THREAD

**Issue by trim21** [Asvel/ffxiv-gearing#13]
https://asvel.github.io/ffxiv-gearing/?kgC94XHFXZbTHEVUJ09MD6czOZGBEGtH1E4XuWFq8LmM

![image](https://user-images.githubusercontent.com/13553903/115744411-2172f980-a3c5-11eb-91a6-5c0246f5d43c.png)

这个是用来区分左右戒指的吗

**Comment by Asvel** [comment]
是的，是特性。
想获得更常规的格式可以参考这里：[src/stores/Store.ts#L270](https://github.com/Asvel/ffxiv-gearing/blob/10f47def5e833e320265211787a50c624de29e54/src/stores/Store.ts#L270)。

**Comment by trim21** [comment]
谢谢
