### ISSUE TITLE
关于武僧同步后的技速问题

### ISSUE THREAD

**Issue by deepexh** [Asvel/ffxiv-gearing#14]
![image](https://user-images.githubusercontent.com/65269131/126926365-049edf05-bae4-474b-88eb-6c3cd271060c.png)
当同步到70级后，武僧只有3档疾风迅雷，希望可以更新一下~~~

**Comment by Asvel** [comment]
这里个人判断是使用场景不值得付出修改的工作量，目前不打算做，抱歉。

**Comment by Asvel** [comment]
现在同步到80级以下时不再计算速度类buff了。
