### ISSUE TITLE
Building issue related to `package.json` and case sensitive fs

### ISSUE THREAD

**Issue by dsrkafuu** [Asvel/ffxiv-gearing#16]
https://github.com/Asvel/ffxiv-gearing/blob/master/yarn.lock#L52-L346
Some dependencies locked in `yarn.lock` between L52-346 will be missing if using npm/pnpm to install deps directly which causes builds to fail. Manually adding these deps is required to complete the build.

https://github.com/Asvel/ffxiv-gearing/blob/master/src/index.tsx#L7
Also, `app.scss` imported in `index.tsx` can cause resolving issues on case sensitive file-systems:

```
16:06:26.836 | ERROR in ./src/index.tsx 9:0-26
16:06:26.836 | Module not found: Error: Can't resolve './views/app.scss' in '/opt/buildhome/repo/src'
```

**Comment by Asvel** [comment]
Please use yarn, npm is good but this project does not contain a `package-lock.json`, use npm directly will lead to install unverfied version of dependences. From my personal experience, end-user oriented project is not robust enough on dependences minor version upgrade sometimes, especially these UI related dependences.

Besides, I can't reproduce these missing under npm 7.21.0 and npm 8.1.4, just `npm install & npm start` it works fine, and your Cloudflare Pages build log isn't visible to me, sorry I cannot analyze the detail problem furthermore.

**Comment by Asvel** [comment]
After more investigation, I guess you might use pnpm, they use a "non-flat" strategy, it does break the installation. ~Why you use a package manager that neither the project specificed one (yarn) nor the standard one (npm), of course it won't work!~

Always explicit declaration direct dependences is a kind of convention, not a standard, and this project doesn't follow this convention. Explicit declaration can pin dependences version better but we have the lock file already, and for browser targeted project, avoid bundling mutliply versions of same dependency is same important as keep version determined, so I prefer the flat structure.

From the document of pnpm, you could use `pnpm install --shamefully-hoist`, it should work. (But I still recommend do not ignore the lock file.)

**Comment by dsrkafuu** [comment]
Thanks for your reply and suggestions, I will use yarn in the future🤗
The CloudFlare build issue was caused by an incorrect build cache and has been resolved now.
