### ISSUE TITLE
您好，那是否意味着能在一定条件下自动计算如何打魔晶石最好？

### ISSUE THREAD

**Issue by Ventulus-lab** [Asvel/ffxiv-gearing#17]
你的网站工具真的非常好用。
虽然网上会有各种BIS的帖子，不过我想对大量玩家来说，并不会花费很大的力气去获取版本最强装备。
然后即使是我限定目标只要咸鱼520，实际上大部分时间还是在往这个目标、攒这套装备的过程中。
比如每周一件尼尔装备不一定会出、点数装备攒点数得花好几周时间。

相对于装备，魔晶石是非常好获取的，随便一个玩家打打本都有大量魔晶石用不掉，所以可以随时更换。
那么，能不能开发个功能，玩家选好当前的一套装备后，自动计算一下如何打魔晶石，理论输出最高？魔晶石孔位有限，让程序穷举一下应该不会很难吧。
如果是我人手动选的话，由于副属性可能达到一个比较平衡的状态，并不是无脑堆一个，一会这个高一会那个高，手动选就比较吃力

**Comment by Asvel** [comment]
如果可行的话我也想让程序自动选好魔晶石甚至是装备本身，但实战中一套配装的性能远非一个“每威力伤害期望”就足以妥善评估，忽视职业技能机制无脑看这个参数带来的偏差并不亚于无脑暴>直>信打上去的性能损失，所以其实这种功能的很难有多少实用价值。
