### ISSUE TITLE
食物属性修正：亚考牛慕沙卡HQ

### ISSUE THREAD

**Issue by wangzy77** [Asvel/ffxiv-gearing#19]
选择“捕鱼人”职业，在下方的食物栏中，“亚考牛慕沙卡HQ”采集力buff上限为55，但游戏中上限为48
![1](https://user-images.githubusercontent.com/14155555/171789417-bcbf6db2-5a47-492c-b9f2-c74305873d1e.png)
![2](https://user-images.githubusercontent.com/14155555/171789426-1e502aff-211f-468d-9f63-e2a510bb1c04.png)

**Comment by Asvel** [comment]
6.1改成55了，版本更新改旧道具属性的情况比较罕见，现在是直接按国际服的数据来。
