### ISSUE TITLE
新特性请求：非D青模式

### ISSUE THREAD

**Issue by oukenteikan** [Asvel/ffxiv-gearing#22]
希望在“设置”中添加一个选项能够手动关闭“以太复制：进攻”的计算，以满足对T青或N青配装的需求。

**Comment by Asvel** [comment]
我考虑一下。

**Comment by Asvel** [comment]
抱歉，我不想在这里再增加更多的复杂度，固定为D青模式是考虑到实践中一般更关注D青的输出，权衡之下选了以D青为基准，如果这个特性不合适的话可以整个下掉，不打算做开关。

**Comment by oukenteikan** [comment]
确实提出的需求过于小众了。考虑常驻D青buff已经是是非常体贴的特性！
