### ISSUE TITLE
数据不一致：525装等头手脚耐力值均有偏差

### ISSUE THREAD

**Issue by oukenteikan** [Asvel/ffxiv-gearing#23]
![image](https://user-images.githubusercontent.com/33342734/208364981-da8b1700-9cbf-4eb6-881e-9be04f0d2ee9.png)

![image](https://user-images.githubusercontent.com/33342734/208365156-87432c06-0779-4d8d-a232-caf9ac9dd935.png)

**Comment by Asvel** [comment]
感谢反馈，晚些时候修复。

**Comment by Asvel** [comment]
已修复。
