### ISSUE TITLE
想要支持自定义的装备导入

### ISSUE THREAD

**Issue by anjin1999** [Asvel/ffxiv-gearing#24]
最近在研究ulk配装 优武的副属性也想要计入考量范围内 并且法系的小红衣在装备库中无法找到qwq 可能是由于占用两个装备位置的原因 期待更新(*❦ω❦)

**Comment by Asvel** [comment]
这是一个bug，我修一下。~~我竟然一直没注意到存在这个问题。~~

**Comment by Asvel** [comment]
已修复。没有做“头部无法装备其他物品”方面的逻辑，用的时候注意一下吧。
