### ISSUE TITLE
优雷卡法系和奶妈的补正衣无法再配装里选择

### ISSUE THREAD

**Issue by Zuokeluobang** [Asvel/ffxiv-gearing#25]
优雷卡法系和奶妈的补正衣无法再配装里选择，这两件装备带有帽兜，带上去会顶掉帽子的位置，在配装器里无法选择。我们想探究一套ulk理论最优装备，请问可不可以提供一些如伤害期望计算公式或者装备数据之类的帮助

**Comment by Asvel** [comment]
这是一个bug，我修一下。~~我竟然一直没注意到存在这个问题。~~

**Comment by Asvel** [comment]
已修复。没有做“头部无法装备其他物品”方面的逻辑，用的时候注意一下吧。

**Comment by Zuokeluobang** [comment]
收到，非常感谢您对我提出问题的重视，祝您生活愉快！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月30日(周二) 下午2:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Asvel/ffxiv-gearing] 优雷卡法系和奶妈的补正衣无法再配装里选择 (Issue #25)




 
已修复。没有做“头部无法装备其他物品”方面的逻辑，用的时候注意一下吧。
