### ISSUE TITLE
无法导入特定etro.gg的配装

### ISSUE THREAD

**Issue by edwardez** [Asvel/ffxiv-gearing#27]
https://etro.gg/gearset/4f35df9d-7330-466e-9860-f2771e302922

提示
>未能在此页面中找到支持导入的数据。

![etro](https://github.com/user-attachments/assets/f63fc404-5f4a-4ea5-9fd8-5f76f43308df)

看了一下好像是`state.gearsets.gearset.materia`里，如果某个部位没有打石头value是null，然后https://github.com/Asvel/ffxiv-gearing/blob/master/src/import.js里`const materiaInfo = materiaInfoOfId[materiaId];`就报错了

**Comment by Asvel** [comment]
感谢（这么详细的！）反馈，已修复。

**Comment by edwardez** [comment]
本来是想自己交个pr的，看了下发现是这个问题想着“假如只是空孔就会报错可能早就发现这个bug了吧”就想着应该还是作者自己最清楚代码怎么回事就只交了个issue（

试了下修复了，感谢！
