### ISSUE TITLE
新特性请求：代码层面API，通过分享链接抓取角色属性

### ISSUE THREAD

**Issue by miyehn** [Asvel/ffxiv-gearing#28]
哈喽打扰！请问您考虑把导入部分的逻辑抽出来做成API吗？就像[etro](https://etro.gg/api/docs/)和[xivgear](https://github.com/xiv-gear-planner/gear-planner/blob/master/API_DOC.md)那样。

这么请求的理由是，API能让它很方便和其它工具比如我们的[排轴器 (XIV in the Shell)](https://xivintheshell.com)联动，让国服玩家也能从分享链接直接导入角色属性 :))

**Comment by Asvel** [comment]
抱歉，这是一个纯前端静态项目，部署在 GitHub Pages 上，技术上无法提供任何动态生成型 API 服务。
不过配装信息其实全部存放了在分享链接中，你可以考虑参考 [share.ts](/Asvel/ffxiv-gearing/blob/master/src/share.ts) 在本地直接解析它。

**Comment by Asvel** [comment]
或者我可以提供一个可以单独引入的 js 文件，在浏览器端引入后给 window 添加一个解析分享链接的函数。
这样解析实现可以随我这边更新而更新。

**Comment by miyehn** [comment]
> 或者我可以提供一个可以单独引入的 js 文件，在浏览器端引入后给 window 添加一个解析分享链接的函数。 这样解析实现可以随我这边更新而更新。

这个办法听起来好！可以有的话就太好了！🙏🙏提前替所有用XIV in the Shell的国服玩家感谢您！

**Comment by miyehn** [comment]
在QQ联系上啦，暂定改成从排轴器直接解析一个从这边复制过去的包含角色面板的字符串。
就先关掉这个issue了👌
