### ISSUE TITLE
导出数据有误

### ISSUE THREAD

**Issue by ghost** [Asvel/ffxiv-gearing#5]
手镯装备 伊修加德新型咏咒手环 信念8 直击8 信念7 信念7 咏唱7
在导出数据后，咏唱7会消失
[示例](https://asvel.github.io/ffxiv-gearing/?6hq7wLA4MfXkAUN7oNuS5r5OW9EdgH9DLBkOdIZfnZjpE0c0q2bYfDWRdE88e5QqEP)

**Comment by Asvel** [comment]
感谢反馈，已修复。
