### ISSUE TITLE
可以直接外链🐎

### ISSUE THREAD

**Issue by NepPure** [Asvel/ffxiv-gearing#6]
https://www.ffxiv.cn/

虽然是非常大气的MIT，还是问一下大佬

**Comment by Asvel** [comment]
可以的，请自由使用。

**Comment by NepPure** [comment]
Github Page确实大陆访问太慢了，网站访问用户比较多，所以用https://gearing.ffsusu.com/ 套了一个CDN ，向大佬报备

**Comment by Asvel** [comment]
麻烦大佬了，需要我提供什么支持吗。

**Comment by trim21** [comment]
@NepPure 请问能不能同步一下上游的更新？

**Comment by NepPure** [comment]
> @NepPure 请问能不能同步一下上游的更新？

我印象里我同步了 原来我没同步 没事了
