### ISSUE TITLE
feature request: 等级和装等同步

### ISSUE THREAD

**Issue by trim21** [Asvel/ffxiv-gearing#7]
绝本没有对应装等同步的木桩…（

**Comment by Asvel** [comment]
咕咕，咕咕咕！
好像在说 “在做了在做了，正好幻巧战也要用到”。

**Comment by trim21** [comment]
这个装备的DLY是什么属性啊，怎么wiki上没有对应的。。。

**Comment by trim21** [comment]
要同步435的话根本都不知道主属性和副属性应该同步到多少，现成有装备的倒是可以直接看装备知道数值。

想了下需要同步的装等也就345，375，和475 以及不知道具体数值的435，我大概先尝试实现一下 <del>这三个装等</del> 470的同步

忘记了4.0时候的计算公式还不一样

**Comment by Asvel** [comment]
抱歉久等，最近身体不太好，还碰上得在 5.30 肝完的创造之手成就比较忙，我尽量在这几天做完它。

逻辑部分我已经完成了，现在在做 UI，虽然用不上了但还是感谢你的 PR。

DLY 是武器攻击间隔，一个纯用于展示的数值，物理职业也许会需要看。

品级同步的上限和镶嵌的属性上限是同一个，由品级参数、部位参数、职能参数计算得出，这三项都包含在了游戏本地数据里可以解包得到，计算方式可以看[这篇文章](https://github.com/xivapi/ffxiv-datamining/blob/master/docs/ItemStats.md#max-meld-values)，我的实现里 getCaps 就是算它的，不用打表。

**Comment by Asvel** [comment]
搞定了，用用看吧。

现在同步后的伤害期望可能不太准，特别是50级60级T职的，没找到测好的参数自己粗略测了一个，先这样吧等忙完这期重建再说。

**Comment by trim21** [comment]
感谢
