### ISSUE TITLE
导入功能无法正常工作，不太确定问题在哪里

### ISSUE THREAD

**Issue by trim21** [Asvel/ffxiv-gearing#9]
表现是导入之后浏览器直接freeze了，打开console也没有看到报错

尝试了下镜像的那个旧版本（ https://gearing.ffsusu.com/ ）倒是可以正常工作

尝试导入 https://etro.gg/gearset/6592f0da-cebb-43c7-a939-22707b184ca0

[生成的URL](https://asvel.github.io/ffxiv-gearing/?import-%7B%22job%22%3A%22GNB%22%2C%22level%22%3A80%2C%22gears%22%3A%5B%7B%22id%22%3A28304%2C%22materias%22%3A%5B%5B%22CRT%22%2C8%5D%2C%5B%22CRT%22%2C8%5D%2C%5B%22DHT%22%2C8%5D%5D%7D%2C%7B%22id%22%3A25566%2C%22materias%22%3A%5B%5B%22DHT%22%2C8%5D%2C%5B%22DHT%22%2C8%5D%5D%7D%2C%7B%22id%22%3A30617%2C%22materias%22%3A%5B%5B%22DHT%22%2C8%5D%2C%5B%22DHT%22%2C8%5D%5D%7D%2C%7B%22id%22%3A26955%2C%22materias%22%3A%5B%5B%22DHT%22%2C8%5D%2C%5B%22DHT%22%2C8%5D%5D%7D%2C%7B%22id%22%3A25571%2C%22materias%22%3A%5B%5B%22DHT%22%2C8%5D%2C%5B%22DHT%22%2C8%5D%5D%7D%2C%7B%22id%22%3A29058%2C%22materias%22%3A%5B%5D%7D%2C%7B%22id%22%3A30620%2C%22materias%22%3A%5B%5B%22CRT%22%2C8%5D%2C%5B%22DHT%22%2C8%5D%5D%7D%2C%7B%22id%22%3A30658%2C%22materias%22%3A%5B%5B%22DET%22%2C8%5D%5D%7D%2C%7B%22id%22%3A25613%2C%22materias%22%3A%5B%5B%22DHT%22%2C8%5D%2C%5B%22DHT%22%2C8%5D%5D%7D%2C%7B%22id%22%3A27005%2C%22materias%22%3A%5B%5B%22DHT%22%2C8%5D%2C%5B%22DHT%22%2C8%5D%5D%7D%2C%7B%22id%22%3A27010%2C%22materias%22%3A%5B%5B%22CRT%22%2C8%5D%2C%5B%22DHT%22%2C8%5D%5D%7D%2C%7B%22id%22%3A25623%2C%22materias%22%3A%5B%5B%22CRT%22%2C8%5D%2C%5B%22CRT%22%2C8%5D%5D%7D%2C%7B%22id%22%3A29501%2C%22materias%22%3A%5B%5D%7D%5D%7D)

**Comment by Asvel** [comment]
感谢反馈，已修复。

问题出在较早执行的逻辑里，请重新导入，不要点开上面的“生成的URL”哦。
